version: "3"
services:

  mariadb-server:
    image: mariadb:latest
    container_name: mariadb-server
    restart: always
    networks:
      - backend
    environment:
      - MYSQL_ROOT_PASSWORD=OrangeMakers2021

  wordpress:
    image: wordpress:latest
    container_name: wordpress
    restart: always
    networks:
      - backend
    ports:
      - "80:80"
    environment:
      - WORDPRESS_DB_HOST=mariadb-server
      - WORDPRESS_DB_USER=wpuser
      - WORDPRESS_DB_PASSWORD=OrangeMakers2021
      - WORDPRESS_DB_NAME=wpdb

  myadmin:
    image: phpmyadmin:latest
    container_name: myadmin
    restart: always
    networks:
      - backend
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=mariadb-server
    depends_on:
      - "mariadb-server"

networks:
  backend: