version: "3"
services:

  mysql:
    image: mariadb:latest
    container_name: mariadb-server
    restart: always
    networks:
      - backend
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=OrangeMakers2021

  myadmin:
    image: phpmyadmin:latest
    container_name: myadmin
    restart: always
    networks:
      - backend
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=${ROOTPASSWORD}
    depends_on:
      - "mysql"

networks:
  backend:

# volumes:
#   db-data: